name: Release
# this workflow pushes docker images to textile/bidbot for updates on main branch, any version tags, and commits with `[shipit]` in message.
# it also creates new releases with linux binaries on GitHub for any version tags.

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

jobs:
  release:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') || contains(github.event.head_commit.message, '[shipit]')
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: textile/bidbot
          tags: |
            type=edge,branch=main
            type=semver,pattern={{version}}
            type=sha,prefix=sha-

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Buildx patch
        run: |
          file="./Dockerfile"
          echo "patching timestamp for $file"
          touch "$file"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Cache Go resources for linux
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build binary
        if: startsWith(github.ref, 'refs/tags/v')
        run: make build && mv bidbot bidbot-linux-amd64

      - name: Create versioned release for linux
        if: startsWith(github.ref, 'refs/tags/v')
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ github.token }}"
          prerelease: false
          files: |
            LICENSE
            bidbot-*
